/**
 * Smoke Test P0 - OpenClaw Aurora App Factory
 *
 * Testa o workflow code-only com execução real:
 * 1. Cria diretório e arquivos
 * 2. Executa comandos (npm install, tsc)
 * 3. Gera relatório
 *
 * Uso: npx ts-node scripts/smoke-test-p0.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { FileMaterializeSkill, FilePlan } from '../src/skills/file/materialize';
import { ExecRunSafeSkill, CommandPlan } from '../src/skills/execution/run-safe';
import { ArtifactCollectSkill } from '../src/skills/artifact/collect';

// ============================================================================
// CONFIG
// ============================================================================

const TEST_APP_NAME = `smoke-test-${Date.now()}`;
const APPS_DIR = './apps';
const RUNS_DIR = './runs';

// ============================================================================
// MAIN
// ============================================================================

async function main() {
  console.log('╔════════════════════════════════════════════════════════════╗');
  console.log('║        OpenClaw Aurora P0 - Smoke Test                     ║');
  console.log('╚════════════════════════════════════════════════════════════╝');
  console.log();

  const executionId = `smoke-${Date.now()}`;
  const startTime = Date.now();
  const results: {
    step: string;
    status: 'PASS' | 'FAIL';
    message: string;
    duration?: number;
  }[] = [];

  // Criar diretórios base
  if (!fs.existsSync(APPS_DIR)) {
    fs.mkdirSync(APPS_DIR, { recursive: true });
  }
  if (!fs.existsSync(RUNS_DIR)) {
    fs.mkdirSync(RUNS_DIR, { recursive: true });
  }

  console.log(`App Name: ${TEST_APP_NAME}`);
  console.log(`Execution ID: ${executionId}`);
  console.log();

  // ========================================================================
  // STEP 1: file.materialize
  // ========================================================================
  console.log('─'.repeat(60));
  console.log('STEP 1: file.materialize');
  console.log('─'.repeat(60));

  const fileMaterialize = new FileMaterializeSkill();
  const files: FilePlan[] = [
    {
      path: 'package.json',
      content: JSON.stringify({
        name: TEST_APP_NAME,
        version: '1.0.0',
        scripts: {
          build: 'tsc',
          start: 'node dist/index.js',
        },
        devDependencies: {
          typescript: '^5.0.0',
        },
      }, null, 2),
    },
    {
      path: 'tsconfig.json',
      content: JSON.stringify({
        compilerOptions: {
          target: 'ES2020',
          module: 'commonjs',
          outDir: './dist',
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
        },
        include: ['src/**/*'],
      }, null, 2),
    },
    {
      path: 'src/index.ts',
      content: `// ${TEST_APP_NAME} - Entry point
console.log('Hello from ${TEST_APP_NAME}!');
export const version = '1.0.0';
`,
    },
    {
      path: '.gitignore',
      content: 'node_modules/\ndist/\n',
    },
    {
      path: 'README.md',
      content: `# ${TEST_APP_NAME}\n\nGenerated by OpenClaw Aurora P0 Smoke Test.\n`,
    },
  ];

  const step1Start = Date.now();
  const materializeResult = await fileMaterialize.run({
    params: {
      appName: TEST_APP_NAME,
      basePath: APPS_DIR,
      files,
    },
  });

  const step1Duration = Date.now() - step1Start;

  if (materializeResult.success) {
    const data = materializeResult.data;
    console.log(`✅ PASS: Materialized ${data.filesWritten?.length || 0} files`);
    console.log(`   App Location: ${data.appLocation}`);
    console.log(`   Total Bytes: ${data.totalBytes}`);
    results.push({ step: 'file.materialize', status: 'PASS', message: `${data.filesWritten?.length} files created`, duration: step1Duration });
  } else {
    console.log(`❌ FAIL: ${materializeResult.error}`);
    results.push({ step: 'file.materialize', status: 'FAIL', message: materializeResult.error || 'Unknown error', duration: step1Duration });
  }
  console.log();

  // ========================================================================
  // STEP 2: Verificar arquivos criados
  // ========================================================================
  console.log('─'.repeat(60));
  console.log('STEP 2: Verify files exist');
  console.log('─'.repeat(60));

  const appLocation = path.join(APPS_DIR, TEST_APP_NAME);
  const expectedFiles = ['package.json', 'tsconfig.json', 'src/index.ts', '.gitignore', 'README.md'];
  let allExist = true;

  for (const file of expectedFiles) {
    const filePath = path.join(appLocation, file);
    if (fs.existsSync(filePath)) {
      console.log(`   ✅ ${file}`);
    } else {
      console.log(`   ❌ ${file} (NOT FOUND)`);
      allExist = false;
    }
  }

  if (allExist) {
    results.push({ step: 'verify-files', status: 'PASS', message: 'All files exist' });
  } else {
    results.push({ step: 'verify-files', status: 'FAIL', message: 'Some files missing' });
  }
  console.log();

  // ========================================================================
  // STEP 3: exec.run_safe (npm install + tsc)
  // ========================================================================
  console.log('─'.repeat(60));
  console.log('STEP 3: exec.run_safe (npm install + tsc --noEmit)');
  console.log('─'.repeat(60));

  const execRunSafe = new ExecRunSafeSkill();
  const commands: CommandPlan[] = [
    { cmd: 'npm', args: ['install'], description: 'Install dependencies' },
    { cmd: 'npx', args: ['tsc', '--noEmit'], description: 'Type check' },
  ];

  const step3Start = Date.now();
  const execResult = await execRunSafe.run({
    params: {
      appLocation,
      commands,
      logDir: `${RUNS_DIR}/${executionId}/logs`,
      executionId,
    },
  });
  const step3Duration = Date.now() - step3Start;

  if (execResult.success) {
    const data = execResult.data;
    console.log(`✅ PASS: Ran ${data.commandsRun?.length || 0} commands`);
    console.log(`   Success: ${data.successCount}, Failed: ${data.failedCount}, Blocked: ${data.blockedCount}`);

    // Show individual command results
    for (const cmd of data.commandsRun || []) {
      const icon = cmd.status === 'success' ? '✅' : cmd.status === 'blocked' ? '🚫' : '❌';
      console.log(`   ${icon} ${cmd.cmd} ${cmd.args.join(' ')} - ${cmd.status} (${(cmd.duration / 1000).toFixed(2)}s)`);
    }

    results.push({
      step: 'exec.run_safe',
      status: data.failedCount === 0 ? 'PASS' : 'FAIL',
      message: `${data.successCount}/${data.commandsRun?.length} commands succeeded`,
      duration: step3Duration,
    });
  } else {
    console.log(`❌ FAIL: ${execResult.error}`);
    results.push({ step: 'exec.run_safe', status: 'FAIL', message: execResult.error || 'Unknown error', duration: step3Duration });
  }
  console.log();

  // ========================================================================
  // STEP 4: artifact.collect
  // ========================================================================
  console.log('─'.repeat(60));
  console.log('STEP 4: artifact.collect');
  console.log('─'.repeat(60));

  const artifactCollect = new ArtifactCollectSkill();
  const step4Start = Date.now();
  const collectResult = await artifactCollect.run({
    params: {
      executionId,
      appName: TEST_APP_NAME,
      appLocation,
      workflow: 'smoke-test',
      filesWritten: materializeResult.data?.filesWritten || [],
      commandsRun: execResult.data?.commandsRun || [],
      workflowSteps: results.map(r => ({
        persona: 'smoke-test',
        subskill: r.step,
        status: r.status === 'PASS' ? 'success' : 'failed',
        duration: r.duration,
      })),
      errors: [],
      startTime,
      endTime: Date.now(),
    },
  });
  const step4Duration = Date.now() - step4Start;

  if (collectResult.success) {
    const data = collectResult.data;
    console.log(`✅ PASS: Artifacts collected`);
    console.log(`   Run Folder: ${data.runFolder}`);
    console.log(`   Report JSON: ${data.reportJson}`);
    console.log(`   Report MD: ${data.reportMd}`);
    console.log(`   Logs: ${data.logsCollected?.length || 0} files`);
    results.push({ step: 'artifact.collect', status: 'PASS', message: `Reports at ${data.runFolder}`, duration: step4Duration });
  } else {
    console.log(`❌ FAIL: ${collectResult.error}`);
    results.push({ step: 'artifact.collect', status: 'FAIL', message: collectResult.error || 'Unknown error', duration: step4Duration });
  }
  console.log();

  // ========================================================================
  // STEP 5: Verificar relatórios
  // ========================================================================
  console.log('─'.repeat(60));
  console.log('STEP 5: Verify reports');
  console.log('─'.repeat(60));

  const runFolder = `${RUNS_DIR}/${executionId}`;
  const reportJsonPath = path.join(runFolder, 'report.json');
  const reportMdPath = path.join(runFolder, 'report.md');

  let reportsExist = true;
  if (fs.existsSync(reportJsonPath)) {
    console.log(`   ✅ report.json exists`);
    const reportJson = JSON.parse(fs.readFileSync(reportJsonPath, 'utf8'));
    console.log(`      Status: ${reportJson.summary?.status}`);
  } else {
    console.log(`   ❌ report.json NOT FOUND`);
    reportsExist = false;
  }

  if (fs.existsSync(reportMdPath)) {
    console.log(`   ✅ report.md exists`);
    const reportMd = fs.readFileSync(reportMdPath, 'utf8');
    console.log(`      Size: ${reportMd.length} bytes`);
  } else {
    console.log(`   ❌ report.md NOT FOUND`);
    reportsExist = false;
  }

  if (reportsExist) {
    results.push({ step: 'verify-reports', status: 'PASS', message: 'Both reports exist' });
  } else {
    results.push({ step: 'verify-reports', status: 'FAIL', message: 'Some reports missing' });
  }
  console.log();

  // ========================================================================
  // SUMMARY
  // ========================================================================
  console.log('═'.repeat(60));
  console.log('SMOKE TEST SUMMARY');
  console.log('═'.repeat(60));

  const totalDuration = Date.now() - startTime;
  const passed = results.filter(r => r.status === 'PASS').length;
  const failed = results.filter(r => r.status === 'FAIL').length;

  console.log();
  for (const r of results) {
    const icon = r.status === 'PASS' ? '✅' : '❌';
    const durationStr = r.duration ? ` (${(r.duration / 1000).toFixed(2)}s)` : '';
    console.log(`${icon} ${r.step}: ${r.message}${durationStr}`);
  }
  console.log();

  console.log(`Total: ${passed} PASS, ${failed} FAIL`);
  console.log(`Duration: ${(totalDuration / 1000).toFixed(2)}s`);
  console.log();

  if (failed === 0) {
    console.log('╔════════════════════════════════════════════════════════════╗');
    console.log('║                    ✅ SMOKE TEST PASSED                    ║');
    console.log('╚════════════════════════════════════════════════════════════╝');
    console.log();
    console.log(`App created at: ${appLocation}`);
    console.log(`Reports at: ${runFolder}`);
    process.exit(0);
  } else {
    console.log('╔════════════════════════════════════════════════════════════╗');
    console.log('║                    ❌ SMOKE TEST FAILED                    ║');
    console.log('╚════════════════════════════════════════════════════════════╝');
    process.exit(1);
  }
}

main().catch((error) => {
  console.error('Smoke test crashed:', error);
  process.exit(1);
});
